version: '3'
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            TZ: Asia/Shanghai
            LANG: en_US.UTF-8
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: nacos
            MYSQL_USER: nacos
            MYSQL_PASSWORD: 123456
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data/:/var/lib/mysql/
            - ./mysql/conf/:/etc/mysql/conf.d/
            - ./mysql/init.d/:/docker-entrypoint-initdb.d/
        command:
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
        networks:
            dev:
                ipv4_address: 172.22.0.5

networks:
    dev:
        external: true