version: '3.4'
services:
    nacos:
    image: nacos/nacos-server:v2.2.3-slim # 镜像`nacos/nacos-server:v2.1.2-slim`
    container_name: nacos # 容器名为'nacos'
    restart: always # 指定容器退出后的重启策略为始终重启
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
        - ./nacos/logs:/home/nacos/logs
    environment:
        TZ: Asia/Shanghai
        LANG: en_US.UTF-8
        MODE: standalone
        SPRING_DATASOURCE_PLATFORM: mysql
        MYSQL_SERVICE_HOST: 172.22.0.5
        MYSQL_SERVICE_DB_NAME: nacos
        MYSQL_SERVICE_USER: root
        MYSQL_SERVICE_PASSWORD: 123456
        JVM_XMS: 256m
        JVM_XMX: 512m
        JVM_XMN: 128m

    ports: # 映射端口
        - "8848:8848"
    networks:
        dev:
        ipv4_address: 172.22.0.6
    external_links:
        - mysql:mysql
        #    depends_on:
        #      - mysql
        #    extends:
        #      file: mysql-docker.yml
        #      service: mysql

networks:
    dev:
    external: true



