version: '3'
services:
    redis:
    image: redis:latest
    container_name: some-redis
    ports:
        - "6379:6379"
    networks:
        dev:
        ipv4_address: 172.22.0.8
networks:
    dev:
    external: true

