version: '3'
services:
    namesrv:
        image: apache/rocketmq-namesrv:4.8.0
        container_name: rocketmq-namesrv
        ports:
            - "9876:9876"

    broker:
        image: apache/rocketmq-broker:4.8.0
        container_name: rocketmq-broker
        ports:
            - "10909:10909"
            - "10911:10911"
        depends_on:
            - namesrv
        environment:
            - "NAMESRV_ADDR=namesrv:9876"

    rocketmq-console:
        image: styletang/rocketmq-console-ng
        container_name: rocketmq-console
        ports:
            - "8080:8080"
        environment:
            - "JAVA_OPTS=-Drocketmq.config.namesrvAddr=namesrv:9876"

